name: FoxPrefix
version: ${project.version}
main: br.foxprefix.Main
authors: [Bryan_lzh]
depend: [BrAPI]

commands:
    FoxPrefix:
        aliases: [fp]
        description: 主命令
        usage: |
            §6/<command> >> 打开UI
            §6/<command> unlock [玩家] [称号] >> 给玩家解锁称号(强制解锁)
            §6/<command> reload >> 重载插件
            §6/<command> delach [玩家] [统计] >> 删除某个玩家的某个统计值